### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by RudyFiero** [automote/ESP-CoAP#3]
I wish I could be more descriptive but I don't know enough yet. I get the following line highlighted.

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

I'm using Arduino 1.6.13 and the current Git version of ESP8266

-----------------------------------------------------------------------------------------

`Arduino: 1.6.13 (Windows 10), Board: "Generic ESP8266 Module, 160 MHz, 40MHz, QIO, 115200, 4M (3M SPIFFS), ck, Disabled, None"

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Print.h:27:0,

                 from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Stream.h:26,

                 from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:38,

                 from C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:27,

                 from sketch\endpoints.c:3:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Printable.h:25:1: error: unknown type name 'class'

 class Print;

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Printable.h:33:1: error: unknown type name 'class'

 class Printable {

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Printable.h:33:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class Printable {

                 ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Stream.h:26:0,

                 from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:38,

                 from C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:27,

                 from sketch\endpoints.c:3:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Print.h:34:1: error: unknown type name 'class'

 class Print {

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Print.h:34:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class Print {

             ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:38:0,

                 from C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:27,

                 from sketch\endpoints.c:3:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Stream.h:38:1: error: unknown type name 'class'

 class Stream: public Print {

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Stream.h:38:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 class Stream: public Print {

             ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:39:0,

                 from C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:27,

                 from sketch\endpoints.c:3:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/IPAddress.h:29:1: error: unknown type name 'class'

 class IPAddress: public Printable {

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/IPAddress.h:29:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 class IPAddress: public Printable {

                ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/IPAddress.h:90:1: error: unknown type name 'IPAddress'

 extern const IPAddress INADDR_NONE;

 ^

In file included from C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:27:0,

                 from sketch\endpoints.c:3:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:41:1: error: unknown type name 'class'

 class UDP: public Stream {

 ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Udp.h:41:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 class UDP: public Stream {

          ^

In file included from sketch\endpoints.c:3:0:

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:114:1: error: unknown type name 'class'

 class CoapOption {

 ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:114:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class CoapOption {

                  ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:121:1: error: unknown type name 'class'

 class CoapPacket {

 ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:121:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class CoapPacket {

                  ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:134:37: error: expected ')' before '&' token

 typedef void (*callback)(CoapPacket &, IPAddress, int);

                                     ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:137:1: error: unknown type name 'class'

 class CoapUri {

 ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:137:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class CoapUri {

               ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:169:1: error: unknown type name 'class'

 class Coap {

 ^

C:\Users\Rudy\Documents\Arduino\libraries\CoAP_simple_library/coap.h:169:12: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class Coap {

            ^

endpoints.c:32: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_well_known_core(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                       ^

endpoints.c:32: error: unknown type name 'coap_packet_t'

endpoints.c:32: error: unknown type name 'coap_packet_t'

 static int handle_get_well_known_core(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                              ^

endpoints.c:33: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                   ^

endpoints.c:33: error: unknown type name 'coap_packet_t'

endpoints.c:33: error: unknown type name 'coap_packet_t'

 static int handle_get_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                          ^

endpoints.c:34: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                   ^

endpoints.c:34: error: unknown type name 'coap_packet_t'

endpoints.c:34: error: unknown type name 'coap_packet_t'

 static int handle_put_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                          ^

endpoints.c:35: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                               ^

endpoints.c:35: error: unknown type name 'coap_packet_t'

endpoints.c:35: error: unknown type name 'coap_packet_t'

 static int handle_get_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                      ^

endpoints.c:36: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                               ^

endpoints.c:36: error: unknown type name 'coap_packet_t'

endpoints.c:36: error: unknown type name 'coap_packet_t'

 static int handle_put_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                      ^

endpoints.c:37: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                             ^

endpoints.c:37: error: unknown type name 'coap_packet_t'

endpoints.c:37: error: unknown type name 'coap_packet_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                    ^

endpoints.c:38: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                             ^

endpoints.c:38: error: unknown type name 'coap_packet_t'

endpoints.c:38: error: unknown type name 'coap_packet_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                    ^

endpoints.c:39: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                             ^

endpoints.c:39: error: unknown type name 'coap_packet_t'

endpoints.c:39: error: unknown type name 'coap_packet_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                    ^

endpoints.c:40: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                             ^

endpoints.c:40: error: unknown type name 'coap_packet_t'

endpoints.c:40: error: unknown type name 'coap_packet_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo);

                                                                                    ^

endpoints.c:65: error: unknown type name 'coap_endpoint_path_t'

 static const coap_endpoint_path_t path_well_known_core = {2, {".well-known", "core"}};

 ^

sketch\endpoints.c:65:1: warning: braces around scalar initializer [enabled by default]

sketch\endpoints.c:65:1: warning: (near initialization for 'path_well_known_core') [enabled by default]

sketch\endpoints.c:65:1: warning: initialization makes integer from pointer without a cast [enabled by default]

sketch\endpoints.c:65:1: warning: (near initialization for 'path_well_known_core') [enabled by default]

sketch\endpoints.c:65:1: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:65:1: warning: (near initialization for 'path_well_known_core') [enabled by default]

sketch\endpoints.c:65:1: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:65:1: warning: (near initialization for 'path_well_known_core') [enabled by default]

endpoints.c:66: error: unknown type name 'coap_endpoint_path_t'

 static const coap_endpoint_path_t path_light_blink = {1, {"light_blink"}};

 ^

sketch\endpoints.c:66:1: warning: braces around scalar initializer [enabled by default]

sketch\endpoints.c:66:1: warning: (near initialization for 'path_light_blink') [enabled by default]

sketch\endpoints.c:66:1: warning: initialization makes integer from pointer without a cast [enabled by default]

sketch\endpoints.c:66:1: warning: (near initialization for 'path_light_blink') [enabled by default]

sketch\endpoints.c:66:1: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:66:1: warning: (near initialization for 'path_light_blink') [enabled by default]

endpoints.c:67: error: unknown type name 'coap_endpoint_path_t'

 static const coap_endpoint_path_t path_request = {1, {"request"}};

 ^

sketch\endpoints.c:67:1: warning: braces around scalar initializer [enabled by default]

sketch\endpoints.c:67:1: warning: (near initialization for 'path_request') [enabled by default]

sketch\endpoints.c:67:1: warning: initialization makes integer from pointer without a cast [enabled by default]

sketch\endpoints.c:67:1: warning: (near initialization for 'path_request') [enabled by default]

sketch\endpoints.c:67:1: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:67:1: warning: (near initialization for 'path_request') [enabled by default]

endpoints.c:68: error: unknown type name 'coap_endpoint_path_t'

 static const coap_endpoint_path_t path_light = {1, {"light"}};

 ^

sketch\endpoints.c:68:1: warning: braces around scalar initializer [enabled by default]

sketch\endpoints.c:68:1: warning: (near initialization for 'path_light') [enabled by default]

sketch\endpoints.c:68:1: warning: initialization makes integer from pointer without a cast [enabled by default]

sketch\endpoints.c:68:1: warning: (near initialization for 'path_light') [enabled by default]

sketch\endpoints.c:68:1: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:68:1: warning: (near initialization for 'path_light') [enabled by default]

endpoints.c:73: error: unknown type name 'coap_endpoint_t'

 const coap_endpoint_t endpoints[] =

 ^

sketch\endpoints.c:75:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_well_known_core, &path_well_known_core, "ct=40"},

     ^

sketch\endpoints.c:75:5: warning: (near initialization for 'endpoints[0]') [enabled by default]

endpoints.c:75: error: 'COAP_METHOD_GET' undeclared here (not in a function)

     {COAP_METHOD_GET, handle_get_well_known_core, &path_well_known_core, "ct=40"},

      ^

endpoints.c:75: error: 'handle_get_well_known_core' undeclared here (not in a function)

     {COAP_METHOD_GET, handle_get_well_known_core, &path_well_known_core, "ct=40"},

                       ^

sketch\endpoints.c:75:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_well_known_core, &path_well_known_core, "ct=40"},

     ^

sketch\endpoints.c:75:5: warning: (near initialization for 'endpoints[0]') [enabled by default]

sketch\endpoints.c:75:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:75:5: warning: (near initialization for 'endpoints[0]') [enabled by default]

sketch\endpoints.c:75:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:75:5: warning: (near initialization for 'endpoints[0]') [enabled by default]

sketch\endpoints.c:76:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_light, &path_light, "ct=0"},

     ^

sketch\endpoints.c:76:5: warning: (near initialization for 'endpoints[1]') [enabled by default]

endpoints.c:76: error: 'handle_get_light' undeclared here (not in a function)

     {COAP_METHOD_GET, handle_get_light, &path_light, "ct=0"},

                       ^

sketch\endpoints.c:76:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_light, &path_light, "ct=0"},

     ^

sketch\endpoints.c:76:5: warning: (near initialization for 'endpoints[1]') [enabled by default]

sketch\endpoints.c:76:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:76:5: warning: (near initialization for 'endpoints[1]') [enabled by default]

sketch\endpoints.c:76:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:76:5: warning: (near initialization for 'endpoints[1]') [enabled by default]

sketch\endpoints.c:77:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_light_blink, &path_light_blink, "ct=0"},

     ^

sketch\endpoints.c:77:5: warning: (near initialization for 'endpoints[2]') [enabled by default]

endpoints.c:77: error: 'handle_get_light_blink' undeclared here (not in a function)

     {COAP_METHOD_GET, handle_get_light_blink, &path_light_blink, "ct=0"},

                       ^

sketch\endpoints.c:77:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_light_blink, &path_light_blink, "ct=0"},

     ^

sketch\endpoints.c:77:5: warning: (near initialization for 'endpoints[2]') [enabled by default]

sketch\endpoints.c:77:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:77:5: warning: (near initialization for 'endpoints[2]') [enabled by default]

sketch\endpoints.c:77:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:77:5: warning: (near initialization for 'endpoints[2]') [enabled by default]

sketch\endpoints.c:78:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_request, &path_request, "ct=0"},

     ^

sketch\endpoints.c:78:5: warning: (near initialization for 'endpoints[3]') [enabled by default]

endpoints.c:78: error: 'handle_get_request' undeclared here (not in a function)

     {COAP_METHOD_GET, handle_get_request, &path_request, "ct=0"},

                       ^

sketch\endpoints.c:78:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_GET, handle_get_request, &path_request, "ct=0"},

     ^

sketch\endpoints.c:78:5: warning: (near initialization for 'endpoints[3]') [enabled by default]

sketch\endpoints.c:78:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:78:5: warning: (near initialization for 'endpoints[3]') [enabled by default]

sketch\endpoints.c:78:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:78:5: warning: (near initialization for 'endpoints[3]') [enabled by default]

sketch\endpoints.c:79:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_request, &path_request, NULL},

     ^

sketch\endpoints.c:79:5: warning: (near initialization for 'endpoints[4]') [enabled by default]

endpoints.c:79: error: 'COAP_METHOD_PUT' undeclared here (not in a function)

     {COAP_METHOD_PUT, handle_put_request, &path_request, NULL},

      ^

endpoints.c:79: error: 'handle_put_request' undeclared here (not in a function)

     {COAP_METHOD_PUT, handle_put_request, &path_request, NULL},

                       ^

sketch\endpoints.c:79:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_request, &path_request, NULL},

     ^

sketch\endpoints.c:79:5: warning: (near initialization for 'endpoints[4]') [enabled by default]

sketch\endpoints.c:79:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:79:5: warning: (near initialization for 'endpoints[4]') [enabled by default]

sketch\endpoints.c:79:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:79:5: warning: (near initialization for 'endpoints[4]') [enabled by default]

sketch\endpoints.c:80:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_light, &path_light, NULL},

     ^

sketch\endpoints.c:80:5: warning: (near initialization for 'endpoints[5]') [enabled by default]

endpoints.c:80: error: 'handle_put_light' undeclared here (not in a function)

     {COAP_METHOD_PUT, handle_put_light, &path_light, NULL},

                       ^

sketch\endpoints.c:80:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_light, &path_light, NULL},

     ^

sketch\endpoints.c:80:5: warning: (near initialization for 'endpoints[5]') [enabled by default]

sketch\endpoints.c:80:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:80:5: warning: (near initialization for 'endpoints[5]') [enabled by default]

sketch\endpoints.c:80:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:80:5: warning: (near initialization for 'endpoints[5]') [enabled by default]

sketch\endpoints.c:81:5: warning: braces around scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_light_blink, &path_light_blink, NULL},

     ^

sketch\endpoints.c:81:5: warning: (near initialization for 'endpoints[6]') [enabled by default]

endpoints.c:81: error: 'handle_put_light_blink' undeclared here (not in a function)

     {COAP_METHOD_PUT, handle_put_light_blink, &path_light_blink, NULL},

                       ^

sketch\endpoints.c:81:5: warning: excess elements in scalar initializer [enabled by default]

     {COAP_METHOD_PUT, handle_put_light_blink, &path_light_blink, NULL},

     ^

sketch\endpoints.c:81:5: warning: (near initialization for 'endpoints[6]') [enabled by default]

sketch\endpoints.c:81:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:81:5: warning: (near initialization for 'endpoints[6]') [enabled by default]

sketch\endpoints.c:81:5: warning: excess elements in scalar initializer [enabled by default]

sketch\endpoints.c:81:5: warning: (near initialization for 'endpoints[6]') [enabled by default]

sketch\endpoints.c:82:5: warning: braces around scalar initializer [enabled by default]

     {(coap_method_t)0, NULL, NULL, NULL}

     ^

sketch\endpoints.c:82:5: warning: (near initialization for 'endpoints[7]') [enabled by default]

endpoints.c:82: error: 'coap_method_t' undeclared here (not in a function)

     {(coap_method_t)0, NULL, NULL, NULL}

       ^

endpoints.c:82: error: expected '}' before numeric constant

     {(coap_method_t)0, NULL, NULL, NULL}

                     ^

endpoints.c:88: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_well_known_core(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                       ^

endpoints.c:88: error: unknown type name 'coap_packet_t'

endpoints.c:88: error: unknown type name 'coap_packet_t'

 static int handle_get_well_known_core(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                              ^

endpoints.c:96: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                   ^

endpoints.c:96: error: unknown type name 'coap_packet_t'

endpoints.c:96: error: unknown type name 'coap_packet_t'

 static int handle_get_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                          ^

endpoints.c:104: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                   ^

endpoints.c:104: error: unknown type name 'coap_packet_t'

endpoints.c:104: error: unknown type name 'coap_packet_t'

 static int handle_put_light_blink(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                          ^

endpoints.c:125: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                               ^

endpoints.c:125: error: unknown type name 'coap_packet_t'

endpoints.c:125: error: unknown type name 'coap_packet_t'

 static int handle_get_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                      ^

endpoints.c:133: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                               ^

endpoints.c:133: error: unknown type name 'coap_packet_t'

endpoints.c:133: error: unknown type name 'coap_packet_t'

 static int handle_put_request(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                      ^

endpoints.c:149: error: unknown type name 'coap_rw_buffer_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                             ^

endpoints.c:149: error: unknown type name 'coap_packet_t'

endpoints.c:149: error: unknown type name 'coap_packet_t'

 static int handle_get_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                    ^

endpoints.c:157: error: unknown type name 'coap_rw_buffer_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                             ^

endpoints.c:157: error: unknown type name 'coap_packet_t'

endpoints.c:157: error: unknown type name 'coap_packet_t'

 static int handle_put_light(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t id_hi, uint8_t id_lo)

                                                                                    ^

sketch\endpoints.c: In function 'build_rsp':

endpoints.c:182: error: unknown type name 'coap_endpoint_t'

     const coap_endpoint_t *ep = endpoints;

     ^

endpoints.c:187: error: request for member 'handler' in something not a structure or union

     while(NULL != ep->handler)

                     ^

endpoints.c:189: error: request for member 'core_attr' in something not a structure or union

         if (NULL == ep->core_attr) {

                       ^

endpoints.c:202: error: request for member 'path' in something not a structure or union

         for (i = 0; i < ep->path->count; i++) {

                           ^

endpoints.c:202: error: request for member 'count' in something not a structure or union

         for (i = 0; i < ep->path->count; i++) {

                                 ^

sketch\endpoints.c:202:23: warning: comparison between pointer and integer [enabled by default]

         for (i = 0; i < ep->path->count; i++) {

                       ^

endpoints.c:206: error: request for member 'path' in something not a structure or union

             strncat(rsp, ep->path->elems[i], len);

                            ^

endpoints.c:206: error: request for member 'elems' in something not a structure or union

             strncat(rsp, ep->path->elems[i], len);

                                  ^

sketch\endpoints.c:206:13: warning: passing argument 2 of 'strncat' makes pointer from integer without a cast [enabled by default]

             strncat(rsp, ep->path->elems[i], len);

             ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:10:0,

                 from sketch\endpoints.c:2:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:34:15: note: expected 'const char * restrict' but argument is of type 'int'

 char  *_EXFUN(strncat,(char *__restrict, const char *__restrict, size_t));

               ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/_ansi.h:65:30: note: in definition of macro '_EXFUN'

 #define _EXFUN(name, proto)  name proto

                              ^

endpoints.c:207: error: request for member 'path' in something not a structure or union

             len -= strlen(ep->path->elems[i]);

                             ^

endpoints.c:207: error: request for member 'elems' in something not a structure or union

             len -= strlen(ep->path->elems[i]);

                                   ^

sketch\endpoints.c:207:13: warning: passing argument 1 of 'strlen' makes pointer from integer without a cast [enabled by default]

             len -= strlen(ep->path->elems[i]);

             ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:10:0,

                 from sketch\endpoints.c:2:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:33:16: note: expected 'const char *' but argument is of type 'int'

 size_t  _EXFUN(strlen,(const char *));

                ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/_ansi.h:65:30: note: in definition of macro '_EXFUN'

 #define _EXFUN(name, proto)  name proto

                              ^

endpoints.c:213: error: request for member 'core_attr' in something not a structure or union

         strncat(rsp, ep->core_attr, len);

                        ^

sketch\endpoints.c:213:9: warning: passing argument 2 of 'strncat' from incompatible pointer type [enabled by default]

         strncat(rsp, ep->core_attr, len);

         ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:10:0,

                 from sketch\endpoints.c:2:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:34:15: note: expected 'const char * restrict' but argument is of type 'const int *'

 char  *_EXFUN(strncat,(char *__restrict, const char *__restrict, size_t));

               ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/_ansi.h:65:30: note: in definition of macro '_EXFUN'

 #define _EXFUN(name, proto)  name proto

                              ^

endpoints.c:214: error: request for member 'core_attr' in something not a structure or union

         len -= strlen(ep->core_attr);

                         ^

sketch\endpoints.c:214:9: warning: passing argument 1 of 'strlen' from incompatible pointer type [enabled by default]

         len -= strlen(ep->core_attr);

         ^

In file included from C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:10:0,

                 from sketch\endpoints.c:2:

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:33:16: note: expected 'const char *' but argument is of type 'const int *'

 size_t  _EXFUN(strlen,(const char *));

                ^

C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/libc/xtensa-lx106-elf/include/_ansi.h:65:30: note: in definition of macro '_EXFUN'

 #define _EXFUN(name, proto)  name proto

                              ^

exit status 1
unknown type name 'coap_rw_buffer_t'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by PravallikaNagesh** [comment]
Hello RudyFiero ,
I have gone through the issue,it may be the issue with core ESP8266 libraries.
I will brief you with procedure to be followed to include the libraries of ESP8266 and to use this library.
- The Arduino IDE version of mine is 1.8.1
- To add ESP8266 libraries ,click on file->preferences->
paste this url 'http://arduino.esp8266.com/stable/package_esp8266com_index.json' in the field Additional        boards managers url,->ok.
Go to tools ->board->board manager->scroll down and search for 'esp8266 by ESP8266 Community version 2.3.0,install this package.
- Now clone ESP-CoAP library and add to the adruino libraries go to sketches ->include libraries ->add zib library->select the downloaded ESP-CoAP zip file.This will include the ESP-CoAP library.
- Go to files->examples->ESP_CoAP simple library ->select an example code,compile and flash it onto ESP8266,make client server setup and check if it works.
Hope this will help you.
