### ISSUE TITLE
Is this code communicate with Arduino serial monitor ? or directly have to code in esp8266

### ISSUE THREAD

**Issue by sravan7** [automote/ESP-CoAP#4]
@automote @PravallikaNagesh @AmitSharma1094 @suresh02es @sankar10  @ajitsh @lovelesh 
If it is possible can you tell me where to connect Tx, and Rx pins of esp8266 to Arduino is it 0 (RX)and 1(Tx) or you defined some other pins.

**Comment by lovelesh** [comment]
@sravan7 you can connect the TX/RX of ESP8266 to Arduino TX/RX pins via level shifter. Otherwise alternate approach would be to connect to FTDI on 3.3V as ESP only supports 3.3V only.
