### ISSUE TITLE
How to add options in the packet?

### ISSUE THREAD

**Issue by amila-uk-92** [automote/ESP-CoAP#9]
I'm trying to use options in the standard packet format and the server that I'm using, need resource path as options. I couldn't figure out how to set it in the client programme.

**Comment by lovelesh** [comment]
@Anjeldethwings to add a new option as header in CoAP packet. you can edit this function `uint16_t coapClient::sendPacket(coapPacket &packet, IPAddress ip, int port)`. it contains `// make option header` where you can add your given option provided in coap.h or even add your own option.

**Comment by amila-uk-92** [comment]
thank you. I'm on it.
